#!/bin/bash
for file in docs/*.tex; do
  sed -i 's/ℂ/$\\mathbb{C}$/g' "$file"
  sed -i 's/ℕ/$\\mathbb{N}$/g' "$file"
  sed -i 's/ℝ/$\\mathbb{R}$/g' "$file"
  sed -i 's/𝓝/$\\mathcal{N}$/g' "$file"
  sed -i 's/∀/$\\forall$/g' "$file"
  sed -i 's/∃/$\\exists$/g' "$file"
  sed -i 's/→/$\\to$/g' "$file"
  sed -i 's/↔/$\\leftrightarrow$/g' "$file"
  sed -i 's/∧/$\\land$/g' "$file"
  sed -i 's/∨/$\\lor$/g' "$file"
  sed -i 's/¬/$\\neg$/g' "$file"
  sed -i 's/∈/$\\in$/g' "$file"
  sed -i 's/∉/$\\notin$/g' "$file"
  sed -i 's/⊆/$\\subseteq$/g' "$file"
  sed -i 's/∩/$\\cap$/g' "$file"
  sed -i 's/∪/$\\cup$/g' "$file"
  sed -i 's/∅/$\\emptyset$/g' "$file"
  sed -i 's/≤/$\\le$/g' "$file"
  sed -i 's/≥/$\\ge$/g' "$file"
  sed -i 's/≠/$\\ne$/g' "$file"
  sed -i 's/λ/$\\lambda$/g' "$file"
  sed -i 's/⋂/$\\bigcap$/g' "$file"
  sed -i 's/∘/$\\circ$/g' "$file"
  sed -i 's/‖/$\\|$/g' "$file"
  sed -i 's/↦/$\\mapsto$/g' "$file"
done
